# Generated by Django 5.1.1 on 2024-10-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tmp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tmp_id',
        ),
    ]
