# Generated by Django 5.1.1 on 2024-10-29 18:47

import django.contrib.auth.validators
import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_tmp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90c277b5-3007-4fae-a283-5b13c7fdc523'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='username',
        #     field=models.CharField(default='admin',
        #                            error_messages={'unique': 'A user with that username already exists.'},
        #                            help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        #                            max_length=150, unique=True,
        #                            validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
        #                            verbose_name='username'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='user',
            name='tmp_id',
            field=models.UUIDField(default=uuid.UUID('73ad7980-a29a-4a9b-b188-2baa200497a3')),
        ),
        # migrations.RunPython(copy_uuid_to_temp_id)
    ]
