# Generated by Django 5.1.1 on 2024-10-29 18:53

import django.contrib.auth.validators
import uuid
from django.db import migrations, models

def copy_uuid_to_temp_id(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():

        if not user.tmp_id:
            user.tmp_id = uuid.uuid4()
            user.save()

        user.id = user.tmp_id
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_username_alter_user_tmp_id'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='username',
        #     field=models.CharField(default='admin', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2e41b46-159c-49d5-8d0b-c23d75560d0f'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tmp_id',
            field=models.UUIDField(default=uuid.UUID('865e817e-349d-43a3-862f-786e3033bcf1')),
        ),
        # migrations.RunPython(copy_uuid_to_temp_id)
    ]
