# Generated by Django 5.1.1 on 2024-10-29 19:15

from django.db import migrations

def migrate_id_to_uuid(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # Assuming 'id' is the current integer primary key and tmp_id contains the new UUID values
        cursor.execute("UPDATE users_user SET id = tmp_id")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_ids'),
    ]

    operations = [
        migrations.RunPython(migrate_id_to_uuid),
    ]
