# Generated by Django 5.1.1 on 2024-10-29 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20241029_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tmp_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b8b371e-2990-4eb4-8b0c-b23f816cf351'), editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
