services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    links:
      - db
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}

  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_EX_PORT}:${MYSQL_IN_PORT}
    expose:
      - ${MYSQL_EX_PORT}
    volumes:
      - ./db:/var/lib/mysql